// formats/singleRoundDraw.js
// The active default format. Every entrant in a sport gets exactly one
// fixture (a bye if the pool is odd), generated by the constraint-based
// delegation-diversity matcher in core/delegationMatching.js. This is what
// "Generate Schedule" currently produces.
//
// Every format module in this folder exports the same shape:
//   generateSport(sportId, entrants, options) -> { rounds, byes, meta }
// where `rounds` is an array of "matchdays" (arrays of match objects), so
// the venue/time scheduler and the report builder don't need to know or
// care which format produced the fixtures.

import { generateMaxDiversityPairing } from '../core/delegationMatching.js';

let matchCounter = 0;

export function resetMatchCounter() {
  matchCounter = 0;
}

function nextMatchId() {
  matchCounter += 1;
  return `M${matchCounter}`;
}

export function generateSport(sportId, entrants) {
  const { pairs, byes } = generateMaxDiversityPairing(entrants);
  const matches = pairs.map(({ a, b, sameDelegation }) => ({
    id: nextMatchId(),
    sport: sportId,
    entrantA: a,
    entrantB: b,
    clash: sameDelegation ? a.delegation : null,
  }));
  return {
    rounds: matches.length ? [matches] : [],
    byes,
    meta: { format: 'singleRoundDraw', totalEntrants: entrants.length, fixtureCount: matches.length },
  };
}
